//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vserv.Accounting.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLog
    {
        public long LogId { get; set; }
        public string AppDomain { get; set; }
        public string AspnetCache { get; set; }
        public string AspnetContext { get; set; }
        public string AspnetRequest { get; set; }
        public string AspnetSession { get; set; }
        public System.DateTime Date { get; set; }
        public string Exception { get; set; }
        public string Identity { get; set; }
        public string Level { get; set; }
        public Nullable<int> Line { get; set; }
        public string Logger { get; set; }
        public string Message { get; set; }
        public string Method { get; set; }
        public string NDC { get; set; }
        public string Property { get; set; }
        public string StackTrace { get; set; }
        public string StackTraceDetail { get; set; }
        public Nullable<long> TimeStamp { get; set; }
        public string Thread { get; set; }
        public string Type { get; set; }
        public string Username { get; set; }
        public System.DateTime UTCDate { get; set; }
    }
}
