//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vserv.Accounting.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationLog
    {
        public long LogId { get; set; }
        public string appdomain { get; set; }
        public string aspnetcache { get; set; }
        public string aspnetcontext { get; set; }
        public string aspnetrequest { get; set; }
        public string aspnetsession { get; set; }
        public System.DateTime date { get; set; }
        public string exception { get; set; }
        public string identity { get; set; }
        public string level { get; set; }
        public Nullable<int> line { get; set; }
        public string logger { get; set; }
        public string message { get; set; }
        public string method { get; set; }
        public string ndc { get; set; }
        public string property { get; set; }
        public string stacktrace { get; set; }
        public string stacktracedetail { get; set; }
        public Nullable<long> timestamp { get; set; }
        public string thread { get; set; }
        public string type { get; set; }
        public string username { get; set; }
        public System.DateTime utcdate { get; set; }
    }
}
