//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vserv.Accounting.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeAddresses = new HashSet<EmployeeAddress>();
        }
    
        public int EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string UniversalAccountNumber { get; set; }
        public string PermanentAccountNumber { get; set; }
        public string AADHAARNumber { get; set; }
        public string MobileNumber { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime BirthDay { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> RelievingDate { get; set; }
        public string VBS_Id { get; set; }
        public int DesignationId { get; set; }
        public int SalutationId { get; set; }
        public int GenderId { get; set; }
        public int OfficeBranchId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual OfficeBranch OfficeBranch { get; set; }
        public virtual Salutation Salutation { get; set; }
        public virtual ICollection<EmployeeAddress> EmployeeAddresses { get; set; }
    }
}
