//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vserv.Accounting.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSalaryDetail
    {
        public EmpSalaryDetail()
        {
            this.EmpSalaryDetailArchives = new HashSet<EmpSalaryDetailArchive>();
        }
    
        public int EmpSalaryDetailId { get; set; }
        public int EmployeeId { get; set; }
        public int SalaryComponentId { get; set; }
        public int EmpSalaryStructureId { get; set; }
        public int MonthId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmpSalaryStructure EmpSalaryStructure { get; set; }
        public virtual LookupMonth LookupMonth { get; set; }
        public virtual SalaryComponent SalaryComponent { get; set; }
        public virtual ICollection<EmpSalaryDetailArchive> EmpSalaryDetailArchives { get; set; }
    }
}
