//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vserv.Accounting.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeTaxRate
    {
        public int IncomeTaxRateId { get; set; }
        public System.Guid BatchId { get; set; }
        public string IncomeSlab { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> MinNetTaxableIncome { get; set; }
        public Nullable<decimal> MaxNetTaxableIncome { get; set; }
        public Nullable<int> TaxPercentageRate { get; set; }
        public int DisplayOrder { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime EffectiveTo { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
