//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vserv.Accounting.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySheet
    {
        public int PaySheetId { get; set; }
        public int EmployeeId { get; set; }
        public decimal CTCPerMonth { get; set; }
        public decimal Basic { get; set; }
        public decimal HRA { get; set; }
        public Nullable<decimal> Conveyance { get; set; }
        public decimal SpecialAllowance { get; set; }
        public decimal PerformanceIncentive { get; set; }
        public Nullable<decimal> LeaveEncashment { get; set; }
        public Nullable<decimal> SalaryArrears { get; set; }
        public Nullable<decimal> CabDeductions { get; set; }
        public Nullable<decimal> OtherDeduction { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Others { get; set; }
        public Nullable<decimal> Medical { get; set; }
        public Nullable<decimal> FoodCoupons { get; set; }
        public Nullable<decimal> ProjectIncentive { get; set; }
        public Nullable<decimal> CarLease { get; set; }
        public Nullable<decimal> LTC { get; set; }
        public decimal PF { get; set; }
        public decimal Mediclaim { get; set; }
        public decimal Gratuity { get; set; }
        public Nullable<int> Month { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
