//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vserv.Accounting.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Roles = new HashSet<Role>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string LoweredUserName { get; set; }
        public string DisplayName { get; set; }
        public string MobileAlias { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
    
        public virtual ICollection<Role> Roles { get; set; }
    }
}
