//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vserv.Accounting.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSecurityQuestion
    {
        public int UserSecurityQuestionId { get; set; }
        public int UserId { get; set; }
        public int SecurityQuestionId { get; set; }
        public string Answer { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
